<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ResourcesSubtitle</name>
   <tag></tag>
   <elementGuidId>16581690-c160-4eff-ade0-056967546d25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//h3[@class='resourceSubtitleText'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//h3[@class='resourceSubtitleText'])[1]</value>
      <webElementGuid>3834b8db-a028-4575-a270-204434ddc825</webElementGuid>
   </webElementProperties>
</WebElementEntity>
