<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sex-Ddn</name>
   <tag></tag>
   <elementGuidId>121883b0-4a75-4390-b1b4-efaadbaea2a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;Sex&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;Sex&quot;]</value>
      <webElementGuid>c070fc25-f673-46a9-86e1-187b60e2ecdc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
