<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Unknown-Chkbx</name>
   <tag></tag>
   <elementGuidId>cff5d911-b8c3-4000-879f-ffa726bbb8bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Sex_Unknown&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Sex_Unknown&quot;]</value>
      <webElementGuid>60d8abeb-c1ae-4781-9730-ad09ee714fbb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
