<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PI_FirstName-Txtbx</name>
   <tag></tag>
   <elementGuidId>b5f0e88d-5563-4c28-9c80-dfb479e6ba0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name='pi[firstName]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name='pi[firstName]']</value>
      <webElementGuid>55b2207c-1b37-4e30-8c0b-860ddeaf0aa6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
