<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Demographics_Facet</name>
   <tag></tag>
   <elementGuidId>74e0ec0a-42fc-4e0e-a911-5da75f92c577</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()=&quot;Demographics&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()=&quot;Demographics&quot;]</value>
      <webElementGuid>06cd89ea-82c1-4e2b-baa0-aabf1cc3cc01</webElementGuid>
   </webElementProperties>
</WebElementEntity>
