<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HeaderMessage</name>
   <tag></tag>
   <elementGuidId>bbd747e8-f74e-4c77-9c4b-bb35b5fa2b94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='root']/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]</value>
      <webElementGuid>86547fdc-3b0a-47dd-9faa-f1ed49d7551f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
