<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ConfirmDataSubAreDeIdenified-Yes-RdoBtn</name>
   <tag></tag>
   <elementGuidId>f90da658-e2ee-4164-acad-a694ac6c8d5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-c-data-de-identified-yes-radio-button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-c-data-de-identified-yes-radio-button&quot;]</value>
      <webElementGuid>fb83987a-57e4-4c9d-bbd3-a9b3c77c9831</webElementGuid>
   </webElementProperties>
</WebElementEntity>
