<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ConfirmDataSubAreDeIdenified-No-RdoBtn</name>
   <tag></tag>
   <elementGuidId>5e9187c5-4223-40ef-8fda-21a12208fafa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-c-data-de-identified-no-radio-button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-c-data-de-identified-no-radio-button&quot;]</value>
      <webElementGuid>ae4dc75b-9785-443e-aaad-fb5a3ddf244e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
