<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NumOfSubjectsIncludInSub-Txtbx</name>
   <tag></tag>
   <elementGuidId>10a1b5f8-772c-48f9-8253-4827893087fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-c-number-of-subjects-included-in-the-submission&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-c-number-of-subjects-included-in-the-submission&quot;]</value>
      <webElementGuid>38df657b-4b5c-44d5-925c-5094a2f1e060</webElementGuid>
   </webElementProperties>
</WebElementEntity>
