<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OpenAccess-ChkBx</name>
   <tag></tag>
   <elementGuidId>7feb9ef6-7523-4e24-83f5-ef9590f4ad43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-c-access-types-open-access-checkbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-c-access-types-open-access-checkbox&quot;]</value>
      <webElementGuid>072a8245-e704-4d6a-834c-f87ac0d363c6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
