<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SpeciesOfSubjects-Dd</name>
   <tag></tag>
   <elementGuidId>c538162e-5417-41f0-b432-478eda3935ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-c-species-of-subjects&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-c-species-of-subjects&quot;]</value>
      <webElementGuid>59a75116-008e-4b87-9f93-8dab4b6200fe</webElementGuid>
   </webElementProperties>
</WebElementEntity>
