<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CCDC_Url_Verification</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>22e69b9a-1d7f-4839-b13a-1b3b3ba0ae82</testSuiteGuid>
   <testCaseLink>
      <guid>a450a862-1258-4d2c-9246-b67cafc65f84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CCDC_TestCases/Participating Resources page/TC03_CCDC_Resource_page_url_verification</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5b86940b-f1eb-4a00-a3ca-ed4250a41c87</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CCDC/CCDC_ResourcesURL</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>5b86940b-f1eb-4a00-a3ca-ed4250a41c87</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>suffixUrl</value>
         <variableId>5e57f732-11c2-474c-a5a1-6deb12f3344d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5b86940b-f1eb-4a00-a3ca-ed4250a41c87</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ResourceName</value>
         <variableId>eafe31ac-4aa8-424e-a725-e21dd698421e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d6fc784-042c-4456-a85c-468fda0387b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3a1ae93-f74c-4019-95ab-05b1bd00e0fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdb348be-10df-4819-ab04-10c376d15248</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8553112-8a97-469a-be67-faf2a5af50e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5532ce0b-bf07-4aa3-a64b-7778696cbef9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d14d577a-2c72-4ac3-a52c-8e5bf0140cf3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CCDC_TestCases/Search Catalog page/TC03_CCDC_Dataset_page_url_verification</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9431d810-a1bd-4b68-b8f3-69b473592f18</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CCDC/CCDC_DatasetsURL</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>9431d810-a1bd-4b68-b8f3-69b473592f18</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>suffixUrl</value>
         <variableId>e74c2583-3de8-495a-9f54-1a312f149115</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9431d810-a1bd-4b68-b8f3-69b473592f18</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>DatasetName</value>
         <variableId>224f01ab-ba09-4649-8baf-7111001a7bca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50704350-a24d-46b9-be49-d3f8ab0d3176</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f475f2b-57e6-4f3f-9739-1857cb9e085d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
