<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CCDC_Url_VerificationResour</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>761066ba-0ac9-4785-a0a5-c918a62eb443</testSuiteGuid>
   <testCaseLink>
      <guid>a450a862-1258-4d2c-9246-b67cafc65f84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CCDC_TestCases/Participating Resources page/TC03_CCDC_Resource_page_url_verification</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5b86940b-f1eb-4a00-a3ca-ed4250a41c87</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CCDC/CCDC_ResourcesURL</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>5b86940b-f1eb-4a00-a3ca-ed4250a41c87</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>suffixUrl</value>
         <variableId>5e57f732-11c2-474c-a5a1-6deb12f3344d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5b86940b-f1eb-4a00-a3ca-ed4250a41c87</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ResourceName</value>
         <variableId>eafe31ac-4aa8-424e-a725-e21dd698421e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d6fc784-042c-4456-a85c-468fda0387b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3a1ae93-f74c-4019-95ab-05b1bd00e0fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdb348be-10df-4819-ab04-10c376d15248</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8553112-8a97-469a-be67-faf2a5af50e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5532ce0b-bf07-4aa3-a64b-7778696cbef9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
