<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WarningBan_Continue_Btn</name>
   <tag></tag>
   <elementGuidId>ef1e4cc2-9546-48d3-8d79-160b56541419</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(text(),&quot;Continue&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[contains(text(),&quot;Continue&quot;)]</value>
      <webElementGuid>4936592a-b018-468b-ba25-1f81b1d5e9d3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
