<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pathology_Chkbx</name>
   <tag></tag>
   <elementGuidId>49ca24a4-75cd-4e1a-90f2-30f90e7a5d82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Pathology&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Pathology&quot;]</value>
      <webElementGuid>aa652cd0-baf4-4c68-a993-c2e46f9a61c5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
