<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>platform_Ddn</name>
   <tag></tag>
   <elementGuidId>729fa634-b10d-4cf2-a4b4-0d5dc83b7601</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;platform&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;platform&quot;]</value>
      <webElementGuid>8b0b0c68-7012-4a04-be11-068bf70e55b2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
