<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Canine_About_Btn</name>
   <tag></tag>
   <elementGuidId>d1af7762-a2b6-4790-aa08-41579bac6f96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='navbar_dropdown_about']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='navbar_dropdown_about']</value>
      <webElementGuid>24999cf5-131f-4465-a102-6c90d0ed8147</webElementGuid>
   </webElementProperties>
</WebElementEntity>
