<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BannerTitle</name>
   <tag></tag>
   <elementGuidId>235d9ada-a7c8-4985-80b1-61e8c54f389a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()='Purpose']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()='Purpose']</value>
      <webElementGuid>02974863-e5b8-46af-bed6-ab7381703c3a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
