<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CTDCLink</name>
   <tag></tag>
   <elementGuidId>ce07219c-b773-4edc-ad99-90804f6c62f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@title='clinical.datacommons.cancer.gov']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@title='clinical.datacommons.cancer.gov']</value>
      <webElementGuid>6936f9a0-f476-45f2-9481-20cb941df99f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
