<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NotReported_Chkbx</name>
   <tag></tag>
   <elementGuidId>514f883f-5ec9-4609-8991-785d2e3afe1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Race_Unknown&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Race_Unknown&quot;]</value>
      <webElementGuid>5771b90d-6522-4d44-b133-ba6f2a997d97</webElementGuid>
   </webElementProperties>
</WebElementEntity>
