<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Race_Ddn</name>
   <tag></tag>
   <elementGuidId>7f8712e7-45c9-4b19-af49-ecc90b8b53c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@id=&quot;Race&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@id=&quot;Race&quot;])[1]</value>
      <webElementGuid>f5f873d2-7a6f-46a0-a1b3-9827d266949f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
