<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IndicationForStudy_Chkbx</name>
   <tag></tag>
   <elementGuidId>6b05a37d-16cb-4485-8300-376a6721841a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Race_Asian&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Race_Asian&quot;]</value>
      <webElementGuid>fa93999c-482d-4ee7-9cb6-952cc8d65ee8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
