<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DataTypesSubmitd-Dd</name>
   <tag></tag>
   <elementGuidId>18941fa1-d9fb-43c8-a946-cc686ae9cc8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-b-repository-0-data-types-submitted&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-b-repository-0-data-types-submitted&quot;]</value>
      <webElementGuid>f245a903-198c-46ba-910a-2950086a32ea</webElementGuid>
   </webElementProperties>
</WebElementEntity>
