<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dbGapPHSNumber-Txtbx</name>
   <tag></tag>
   <elementGuidId>c7c087c3-e778-47cf-b6cf-298dff23aec4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-b-if-yes-provide-dbgap-phs-number&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-b-if-yes-provide-dbgap-phs-number&quot;]</value>
      <webElementGuid>aaf16792-f003-4d3a-84c9-6384c298f93b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
