<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dbGapRegistered-TogleBtn</name>
   <tag></tag>
   <elementGuidId>12e6585c-813d-4187-9eac-2106f65d467b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-b-dbGaP-registration&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-b-dbGaP-registration&quot;]</value>
      <webElementGuid>8916c38b-7965-45f9-9581-78927110f651</webElementGuid>
   </webElementProperties>
</WebElementEntity>
