<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FundingAgency-Dd</name>
   <tag></tag>
   <elementGuidId>ff422df4-059b-4448-bcbf-432c9ffb55b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-b-funding-agency-organization&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-b-funding-agency-organization&quot;]</value>
      <webElementGuid>64f2787a-9226-4ab0-bcd7-535611ba663f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
