<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GrantContractNumber-Txtbx</name>
   <tag></tag>
   <elementGuidId>fd0d83d5-009c-4bf0-b19b-4e9401a90549</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-b-grant-or-contract-numbers&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-b-grant-or-contract-numbers&quot;]</value>
      <webElementGuid>7da1255f-621d-4f99-8f57-d3c1c0c56e46</webElementGuid>
   </webElementProperties>
</WebElementEntity>
