<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NciGenProgAdministrator-Txtbx</name>
   <tag></tag>
   <elementGuidId>2234939e-ac41-4d43-8d18-86bb77a495f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-b-nci-genomic-program-administrator&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-b-nci-genomic-program-administrator&quot;]</value>
      <webElementGuid>9c2af3b3-fb78-450d-adea-521dad19f3f7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
