<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NCIProgramOfficer-Txtbx</name>
   <tag></tag>
   <elementGuidId>0d4a7cee-9374-43ac-a748-9f75de9aa549</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-b-funding-agency-0-nci-program-officer&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-b-funding-agency-0-nci-program-officer&quot;]</value>
      <webElementGuid>812b29bf-95e8-4392-b29b-92ade281ba08</webElementGuid>
   </webElementProperties>
</WebElementEntity>
