<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProgramAbbreviation-Txtbx</name>
   <tag></tag>
   <elementGuidId>22027554-4a00-4e8b-845f-54130653c654</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-b-program-abbreviation&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-b-program-abbreviation&quot;]</value>
      <webElementGuid>da562af6-9228-4301-b91d-d3cae22a4296</webElementGuid>
   </webElementProperties>
</WebElementEntity>
