<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Program-dd-values</name>
   <tag></tag>
   <elementGuidId>74ad69b6-37e9-4b5f-be72-ac54d8084777</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(text(),'Other')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[contains(text(),'Other')]</value>
      <webElementGuid>bccc0d52-dfbc-4dac-bee7-3e4871acaf1c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
