<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PublicationTitle-TxtBx</name>
   <tag></tag>
   <elementGuidId>c4b043bb-1a8a-46e5-8e5e-eab3db91d3c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-b-publication-1-title&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-b-publication-1-title&quot;]</value>
      <webElementGuid>7d53825c-7fea-452e-b770-adf904fafb67</webElementGuid>
   </webElementProperties>
</WebElementEntity>
