<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StudyTitle-Txtbx</name>
   <tag></tag>
   <elementGuidId>f83bb264-f68b-4e91-a760-56fb7bdff8f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-b-study-title&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-b-study-title&quot;]</value>
      <webElementGuid>4f7e7862-6a2f-42ea-9f61-bbfa4686f571</webElementGuid>
   </webElementProperties>
</WebElementEntity>
