<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StudyID-Txtbx</name>
   <tag></tag>
   <elementGuidId>3938c54a-ef6c-4ef2-a938-c2a81d01629a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-b-study-title&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-b-study-title&quot;]</value>
      <webElementGuid>57d9f921-15f3-4f18-9a0b-e9d0a187e19a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
