<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StudyID-Txtbx</name>
   <tag></tag>
   <elementGuidId>3938c54a-ef6c-4ef2-a938-c2a81d01629a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-b-repository-0-study-id&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-b-repository-0-study-id&quot;]</value>
      <webElementGuid>1f1992c5-f499-43e5-ab97-03b0a0c7f812</webElementGuid>
   </webElementProperties>
</WebElementEntity>
