<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Files-Count</name>
   <tag></tag>
   <elementGuidId>9ad05ca8-4998-437c-b761-c32b4bfb056c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;statsbar_count_4&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;statsbar_count_4&quot;]</value>
      <webElementGuid>b236aa23-c9d2-4f88-bd87-3fef07779089</webElementGuid>
   </webElementProperties>
</WebElementEntity>
