<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Ganglioneuroblastoma-Chkbx</name>
   <tag></tag>
   <elementGuidId>101b8975-55a1-4fc8-b4c3-d4a1c92a992a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Diagnosis_Ganglioneuroblastoma&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Diagnosis_Ganglioneuroblastoma&quot;]</value>
      <webElementGuid>2ac7ff37-9d41-4db8-9509-accf7355565a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
