<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AC_InstitName-Txt</name>
   <tag></tag>
   <elementGuidId>6a86812d-2e32-4d2a-8d18-f8ae88022d62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;review-additional-contacts-0-institution-name-property-value&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;review-additional-contacts-0-institution-name-property-value&quot;]</value>
      <webElementGuid>b31b78e4-417f-4ecb-8a42-b542fc485c5b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
