<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AC_Name-Txt</name>
   <tag></tag>
   <elementGuidId>387d0b2f-c00d-44ff-8686-6694a0ea3b7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;review-additional-contacts-0-name-property-value&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;review-additional-contacts-0-name-property-value&quot;]</value>
      <webElementGuid>07577746-a3af-44b0-999c-c12f4a97348d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
