<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dbGapPHSNumber-Txt</name>
   <tag></tag>
   <elementGuidId>a5402b2a-1a11-4ac2-9e5e-f96c388cd665</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;review-dbGaP-phs-number-property-value&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;review-dbGaP-phs-number-property-value&quot;]</value>
      <webElementGuid>27995093-7d16-424e-9362-41d430304b15</webElementGuid>
   </webElementProperties>
</WebElementEntity>
