<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DOI-Txt</name>
   <tag></tag>
   <elementGuidId>48770379-180d-404c-886d-7defea798bf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;review-existing-publication-0-DOI-property-value&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;review-existing-publication-0-DOI-property-value&quot;]</value>
      <webElementGuid>03e3a93b-8575-4026-8e81-d76c2bc21147</webElementGuid>
   </webElementProperties>
</WebElementEntity>
