<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FndngAgncy-Txt</name>
   <tag></tag>
   <elementGuidId>a780db5c-8c03-4486-aca6-06271faa05a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;review-funding-agency-0-organization-property-value&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;review-funding-agency-0-organization-property-value&quot;]</value>
      <webElementGuid>231b7a01-c041-4510-a3a9-93e700b10505</webElementGuid>
   </webElementProperties>
</WebElementEntity>
