<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GrantCntractNum-Txt</name>
   <tag></tag>
   <elementGuidId>d335f50c-d8f8-4d5f-a530-dc786b6b802e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;review-funding-agency-0-grant-or-contract-numbers-property-value&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;review-funding-agency-0-grant-or-contract-numbers-property-value&quot;]</value>
      <webElementGuid>f4124968-9082-4ca6-8225-cf93faf52034</webElementGuid>
   </webElementProperties>
</WebElementEntity>
