<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Imaging-Txt</name>
   <tag></tag>
   <elementGuidId>d1cb961e-7287-43bf-b7a5-0673abe568e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;review-data-types-imaging-property-value&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;review-data-types-imaging-property-value&quot;]</value>
      <webElementGuid>0c33a20c-43ea-449b-8da3-d52ae36ac5e3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
