<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NCIProgOficer-Txt</name>
   <tag></tag>
   <elementGuidId>ab520268-06ad-457b-b517-d17d9a062671</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;review-funding-agency-0-nci-program-officer-property-value&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;review-funding-agency-0-nci-program-officer-property-value&quot;]</value>
      <webElementGuid>d42f636e-9b48-4ac8-ba8f-a22aef2f284f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
