<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NumOfFiles-RowOne-Txt</name>
   <tag></tag>
   <elementGuidId>c628b996-f649-4f13-a265-78a561fdb1e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;review-file-type-table-file-0-file-count&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;review-file-type-table-file-0-file-count&quot;]</value>
      <webElementGuid>4145e25c-8c52-4444-8acb-b35fe537db70</webElementGuid>
   </webElementProperties>
</WebElementEntity>
