<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NumOfSubjInclud-Txt</name>
   <tag></tag>
   <elementGuidId>9d5dad17-84e3-4ff9-be13-9c302ae0bfbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;review-subjects-number-of-subjects-included-in-the-submission-property-value&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;review-subjects-number-of-subjects-included-in-the-submission-property-value&quot;]</value>
      <webElementGuid>0dc4d599-1b2b-426b-8c82-c3888f602df4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
