<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OtherDataTypes-Txt</name>
   <tag></tag>
   <elementGuidId>cccd8141-56ca-4225-add7-963de3fedcf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;review-data-types-other-data-types-property-value-0&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;review-data-types-other-data-types-property-value-0&quot;]</value>
      <webElementGuid>7b632206-65a2-44b7-9364-8edafe5d5247</webElementGuid>
   </webElementProperties>
</WebElementEntity>
