<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OtherPreCancerTypes-Txt</name>
   <tag></tag>
   <elementGuidId>701f2f1c-a2ec-4998-9fa8-aff770850017</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;review-cancer-types-other-pre-cancer-types-property-value-0&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;review-cancer-types-other-pre-cancer-types-property-value-0&quot;]</value>
      <webElementGuid>149c8c3b-48ea-44ea-aaaa-d873b9457623</webElementGuid>
   </webElementProperties>
</WebElementEntity>
