<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_Name-Txt</name>
   <tag></tag>
   <elementGuidId>fb194f93-9910-4f01-a287-4b8355bac02e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;review-primary-contact-name-property-value&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;review-primary-contact-name-property-value&quot;]</value>
      <webElementGuid>73fdda90-8e56-427b-a67f-7ba78d79d00d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
