<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PI_Email-Txt</name>
   <tag></tag>
   <elementGuidId>08fdd11d-684f-4c53-83f1-53a8147fdd03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;review-pi-email-address-property-value&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;review-pi-email-address-property-value&quot;]</value>
      <webElementGuid>a22e4fde-1409-4b22-bdd7-0418a5736096</webElementGuid>
   </webElementProperties>
</WebElementEntity>
