<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PI_Name-Txt</name>
   <tag></tag>
   <elementGuidId>e0f51631-10a4-404b-b409-1c6d31aa19ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;review-pi-name-property-value&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;review-pi-name-property-value&quot;]</value>
      <webElementGuid>798ec6c2-ba3f-4ce2-9b60-2a31a6885ff5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
