<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PI_Position-Txt</name>
   <tag></tag>
   <elementGuidId>8f004fb4-0ba8-426d-be84-bf71a39d7191</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;review-pi-position-property-value&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;review-pi-position-property-value&quot;]</value>
      <webElementGuid>1b98e800-5853-4c50-bed5-aa6034624727</webElementGuid>
   </webElementProperties>
</WebElementEntity>
