<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RepositoryOtherDataTypes-Txt</name>
   <tag></tag>
   <elementGuidId>31143bd0-7723-4795-a994-169cc3b96a9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;review-repository-0-other-data-types-property-value-0&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;review-repository-0-other-data-types-property-value-0&quot;]</value>
      <webElementGuid>56dc6daf-e5df-4f0e-82f1-cdfec9cda937</webElementGuid>
   </webElementProperties>
</WebElementEntity>
