<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SpeciesOfSubject-Txt</name>
   <tag></tag>
   <elementGuidId>15c98fc0-36af-4eee-8216-83157a36d2ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;review-subjects-species-property-value-0&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;review-subjects-species-property-value-0&quot;]</value>
      <webElementGuid>634b22c0-a892-4cb9-a82e-6151a4fc22dd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
