<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StudyTitle-Txt</name>
   <tag></tag>
   <elementGuidId>d157a895-25c3-44a6-9faf-a4e4326822d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;review-study-information-title-property-value&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;review-study-information-title-property-value&quot;]</value>
      <webElementGuid>0c1e58b2-917b-4674-8271-7b63f95abd09</webElementGuid>
   </webElementProperties>
</WebElementEntity>
