<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Diagnosis-Tbl</name>
   <tag></tag>
   <elementGuidId>aaaacc83-35c3-4051-9f5f-8e12dc7cfd37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='diagnosis_tab_table']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='diagnosis_tab_table']</value>
      <webElementGuid>abe7481e-b4dd-43c9-8966-7d65299655c7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
