<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Diagnosis-Tbl</name>
   <tag></tag>
   <elementGuidId>aaaacc83-35c3-4051-9f5f-8e12dc7cfd37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;diagnosis_tab_table&quot;]/div[3]/table</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;diagnosis_tab_table&quot;]/div[3]/table</value>
      <webElementGuid>c7ca2bd3-0c46-49ba-8d5d-b9fad80b3c13</webElementGuid>
   </webElementProperties>
</WebElementEntity>
