<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Diagnosis-TblHdr</name>
   <tag></tag>
   <elementGuidId>d53380d9-68fa-40e6-87ca-f9aa77d432eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;diagnosis_tab_table&quot;]//thead</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;diagnosis_tab_table&quot;]//thead</value>
      <webElementGuid>33340916-e397-46d2-b29d-20c02ddad154</webElementGuid>
   </webElementProperties>
</WebElementEntity>
