<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Files-TblHdr</name>
   <tag></tag>
   <elementGuidId>1780832f-4950-4bda-ae73-7bc7153b10fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;file_tab_table&quot;]//table//thead</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;file_tab_table&quot;]//table//thead</value>
      <webElementGuid>da483834-a9ea-4b49-9a2e-4a9bd0dc0794</webElementGuid>
   </webElementProperties>
</WebElementEntity>
