<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GeneticAnalysis-Tbl</name>
   <tag></tag>
   <elementGuidId>ba0f1f92-310e-4681-add0-d51e794f957e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='survival_tab_table']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='survival_tab_table']</value>
      <webElementGuid>be16f8af-88ec-4779-823b-dce1b71e0503</webElementGuid>
   </webElementProperties>
</WebElementEntity>
