<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Participants-Tbl</name>
   <tag></tag>
   <elementGuidId>91b95808-b992-451b-a134-c23a460ece02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;participant_tab_table&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;participant_tab_table&quot;]</value>
      <webElementGuid>4eb229b8-f2f0-4b05-8df8-faa270e1a571</webElementGuid>
   </webElementProperties>
</WebElementEntity>
