<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Participants-Tbl</name>
   <tag></tag>
   <elementGuidId>91b95808-b992-451b-a134-c23a460ece02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='participant_tab_table']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='participant_tab_table']</value>
      <webElementGuid>a03905fa-8467-4527-9c27-cf3189f214a5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
