<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Studies-Tbl</name>
   <tag></tag>
   <elementGuidId>80a8adda-3525-49ef-889b-b47c507cc846</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='study_tab_table']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='study_tab_table']</value>
      <webElementGuid>3cb47d05-f2e2-4367-9641-453b7471cf72</webElementGuid>
   </webElementProperties>
</WebElementEntity>
