<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Studies-TblHdr</name>
   <tag></tag>
   <elementGuidId>6e42c1bf-cd1c-427b-9ec0-e73ba31b2e66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;study_tab_table&quot;]//table//thead</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;study_tab_table&quot;]//table//thead</value>
      <webElementGuid>f95e4808-db99-4c30-833b-0e94ef517af4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
