<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Survival-Tbl</name>
   <tag></tag>
   <elementGuidId>9b69511e-5946-4806-842b-fcf802a1ebc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='survival_tab_table']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='survival_tab_table']</value>
      <webElementGuid>86b51a26-9b2c-48e1-ac59-e1305abd03db</webElementGuid>
   </webElementProperties>
</WebElementEntity>
