<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Survival-Tbl</name>
   <tag></tag>
   <elementGuidId>9b69511e-5946-4806-842b-fcf802a1ebc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;survival_tab_table&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;survival_tab_table&quot;]</value>
      <webElementGuid>0d27c2db-89b2-4184-96ba-70750a936580</webElementGuid>
   </webElementProperties>
</WebElementEntity>
