<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TreatmentResp-Tbl</name>
   <tag></tag>
   <elementGuidId>1908a72c-09ec-48c9-8eda-5102fb0d83ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='treatment_response_tab_table']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='treatment_response_tab_table']</value>
      <webElementGuid>7cd3b312-4a62-4032-bea1-5baf253e6282</webElementGuid>
   </webElementProperties>
</WebElementEntity>
