<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Explore-Btn</name>
   <tag></tag>
   <elementGuidId>45b80609-d122-42e0-80a5-3903601f590a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@href,'explore')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@href,'explore')]</value>
      <webElementGuid>73f76abe-27c3-4273-a5fe-a7798a35dc4f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
