<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Survival-Facet</name>
   <tag></tag>
   <elementGuidId>51da4278-56e0-4457-87e7-2de210a0cd31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()=&quot;Survival&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()=&quot;Survival&quot;]</value>
      <webElementGuid>2fd6a31c-27b6-4949-8d17-64f72d0a7a29</webElementGuid>
   </webElementProperties>
</WebElementEntity>
