<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SpotlightTitle1</name>
   <tag></tag>
   <elementGuidId>5af0cc05-51dd-4231-906e-bef4a4dcbdd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//h2)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//h2)[1]</value>
      <webElementGuid>ccc0f4b9-859e-4a35-ac76-5629a1a22aea</webElementGuid>
   </webElementProperties>
</WebElementEntity>
