<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SpotlightTitle1</name>
   <tag></tag>
   <elementGuidId>5af0cc05-51dd-4231-906e-bef4a4dcbdd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h2[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h2[1]</value>
      <webElementGuid>da7eb01d-142d-4142-b5f6-d602b39034e2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
