<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SpotlightTitle3</name>
   <tag></tag>
   <elementGuidId>049b5555-727f-4a43-9d10-85eee850b5e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//h2)[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//h2)[3]</value>
      <webElementGuid>a70bfdd0-0d6e-446d-908e-b68787a118d4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
