<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Projects-Tbl</name>
   <tag></tag>
   <elementGuidId>3e485b9a-879d-4109-a5bb-ab445041ca29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='project_tab_table']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='project_tab_table']</value>
      <webElementGuid>347efd11-797c-4249-9d9b-320cfd7c8316</webElementGuid>
   </webElementProperties>
</WebElementEntity>
