<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Publications-TblHdr</name>
   <tag></tag>
   <elementGuidId>8a4ecc62-a7d3-4f31-878a-d309d6028bae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;publication_tab_table&quot;]//thead</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;publication_tab_table&quot;]//thead</value>
      <webElementGuid>fa5b9523-db33-48f3-8a0c-0d3392ac050d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
