<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Acronym_Ddn</name>
   <tag></tag>
   <elementGuidId>ed2ededb-ac97-4c0b-b639-5facc7a7c73d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@id=&quot;Acronym&quot;])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@id=&quot;Acronym&quot;])[2]</value>
      <webElementGuid>571a9e0e-e3ef-4977-aecd-00f2a33af76c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
