<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ACRYNMPPTC_Chkbx</name>
   <tag></tag>
   <elementGuidId>b5691bb6-4d9c-48fe-8fc7-b202e2281534</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Acronym_PPTC&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Acronym_PPTC&quot;]</value>
      <webElementGuid>0c031d18-1cf4-4237-8c53-244b8f21d8e9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
