<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CCDI_MSK_phs002620_Chkbx</name>
   <tag></tag>
   <elementGuidId>8d3dc792-f7d5-44a1-8f97-a8c69184a1d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Acronym_CCDI_MSK_phs002620&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Acronym_CCDI_MSK_phs002620&quot;]</value>
      <webElementGuid>d1f67e19-edc4-491c-bc6f-bcb2fa0d2f50</webElementGuid>
   </webElementProperties>
</WebElementEntity>
