<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CCDI_UCSF_phs002504_Chkbx</name>
   <tag></tag>
   <elementGuidId>359daf8a-3781-4b16-83a7-a53f0cbaf312</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Acronym_CCDI_UCSF_phs002504&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Acronym_CCDI_UCSF_phs002504&quot;]</value>
      <webElementGuid>ca48736c-8868-450f-ab50-4453cda9e08b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
