<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HTAN_phs002371_Chkbx</name>
   <tag></tag>
   <elementGuidId>1acb2cd4-b1a9-4558-af3c-a004dc20ff1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Acronym_HTAN_phs002371&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Acronym_HTAN_phs002371&quot;]</value>
      <webElementGuid>d975e803-4812-44e6-a40b-9025670d08c1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
