<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CDSResults_Files_Tab</name>
   <tag></tag>
   <elementGuidId>6b7f7c37-e730-4251-a267-b9994b0c9861</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@index='2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@index='2']</value>
      <webElementGuid>6598444d-5004-4552-8f53-081338061ebc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
