<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CDSResults_Participants_Tab</name>
   <tag></tag>
   <elementGuidId>46673fec-efa7-4599-85d1-6c4242584bef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@index='0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@index='0']</value>
      <webElementGuid>39bfccd9-9c0c-4f81-919c-6ecb4db59d15</webElementGuid>
   </webElementProperties>
</WebElementEntity>
