<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sample_Facet</name>
   <tag></tag>
   <elementGuidId>3390e6f2-b2a7-4951-b0f5-97eae9603e4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()=&quot;Samples&quot;]</value>
      <webElementGuid>58ea4ef1-e365-4413-a1c3-c8f72e577b07</webElementGuid>
   </webElementProperties>
</WebElementEntity>
