<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FooterNCITitleLink</name>
   <tag></tag>
   <elementGuidId>9fd695f4-4d63-4b58-a330-88c46549d33a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h1/..</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h1/..</value>
      <webElementGuid>c072489d-2941-41dc-bc29-5a9ba121d657</webElementGuid>
   </webElementProperties>
</WebElementEntity>
