<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Labrador_Chkbx</name>
   <tag></tag>
   <elementGuidId>f9af3a09-e559-4dd3-8142-15fde49ba92d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Breed_Labrador&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Breed_Labrador&quot;]</value>
      <webElementGuid>b1bf7ab8-ddb5-4a3c-a98a-73dc14fed55b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
