<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Newfoundland_Chkbx</name>
   <tag></tag>
   <elementGuidId>e47b891f-bee5-4d18-9408-6aa0c360dd8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='checkbox_Breed_Newfoundland']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='checkbox_Breed_Newfoundland']</value>
      <webElementGuid>02da0c6e-584d-4755-8ba2-e07c5e3a43e6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
