<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GraphQLApiLink</name>
   <tag></tag>
   <elementGuidId>d9ee6d27-38b9-46be-a58b-8b547c54b316</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@href,'graphql')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@href,'graphql')]</value>
      <webElementGuid>3bd2fda0-22d7-4210-a036-6313249e89d4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
