<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BannerTitle</name>
   <tag></tag>
   <elementGuidId>b89efe99-d267-4c0a-9304-c85fa6706b3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='aboutHeaderText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='aboutHeaderText']</value>
      <webElementGuid>93f86ed4-d05e-42cf-ace9-510e72a25b9a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
