<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CCDIDescription</name>
   <tag></tag>
   <elementGuidId>979af0be-538d-420f-8360-3caeb32cff1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='aboutBody']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='aboutBody']</value>
      <webElementGuid>befdbb5d-8273-4ec4-96fc-47cba896ab21</webElementGuid>
   </webElementProperties>
</WebElementEntity>
