<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Response-Ddn</name>
   <tag></tag>
   <elementGuidId>70d40b71-1060-4a07-853f-b1999c52d4f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;Response&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;Response&quot;]</value>
      <webElementGuid>8aea8f74-5936-4c40-b271-f1b9a3fd33bd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
