<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BannerTitle</name>
   <tag></tag>
   <elementGuidId>71fc8561-5de7-45f1-b4e6-1318c6f7e9d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='prDetailHeaderLabel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='prDetailHeaderLabel']</value>
      <webElementGuid>b5164d49-ab03-4d0d-86c7-2f5b051ab620</webElementGuid>
   </webElementProperties>
</WebElementEntity>
