<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DataCommons-Ddn</name>
   <tag></tag>
   <elementGuidId>c1a5e32b-c496-4a26-b1f1-f7c48efffcdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@id=&quot;mui-component-select-dataCommons&quot;])[2]</value>
      <webElementGuid>8dcac3ac-0fd4-4fe1-8b1b-93c485c42c6d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
