<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Study-Ddn</name>
   <tag></tag>
   <elementGuidId>0069d9fe-812e-47e9-9b1e-19630b977318</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='mui-component-select-studyID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='mui-component-select-studyID']</value>
      <webElementGuid>6a576afa-3086-41c7-8d2f-f2b7b472558f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
