<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubmissionLink</name>
   <tag></tag>
   <elementGuidId>a629daee-812c-433f-b7a2-b3f39084fb62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@href,'Template.xlsx')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@href,'Template.xlsx')]</value>
      <webElementGuid>aa832d26-58ee-4246-bbca-287c57ac725f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
