<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Biospecimens-Count</name>
   <tag></tag>
   <elementGuidId>18f2b27c-d093-47fe-ab59-9c6641282df4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;statsbar_count_5&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;statsbar_count_5&quot;]</value>
      <webElementGuid>3019e3c1-41e4-4cfb-a61d-731a9c8d983e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
