<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Diagnoses-Count</name>
   <tag></tag>
   <elementGuidId>83da68d8-1c3d-447f-a0b4-a0f8ab215928</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;statsbar_count_3&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;statsbar_count_3&quot;]</value>
      <webElementGuid>71fd28db-3721-4dfb-91e4-08f65fd26ae9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
