<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Participants-Count</name>
   <tag></tag>
   <elementGuidId>f3519308-52c3-48a4-89f9-4e595f82311b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;statsbar_count_2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;statsbar_count_2&quot;]</value>
      <webElementGuid>e6e3ab50-f1af-4e35-92d0-90a51f323b09</webElementGuid>
   </webElementProperties>
</WebElementEntity>
