<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FooterCRDCLink</name>
   <tag></tag>
   <elementGuidId>ef71fbfd-60bf-4c4e-9e57-27cc6e95198b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[.='CRDC']/..</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[.='CRDC']/..</value>
      <webElementGuid>acabb86a-677c-4b42-b451-d59b1e582714</webElementGuid>
   </webElementProperties>
</WebElementEntity>
