<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AdditionalComnt-TxtBx</name>
   <tag></tag>
   <elementGuidId>799a3154-1d78-49a2-bfcb-2e1e24eaa3d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name='submitterComment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name='submitterComment']</value>
      <webElementGuid>f15e01de-7877-4bb1-a7b5-ccc1e851edee</webElementGuid>
   </webElementProperties>
</WebElementEntity>
