<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ConfirmDataIdentified_no-RdoBtn</name>
   <tag></tag>
   <elementGuidId>8330c0fa-3f95-4f71-b35a-99c128cc5f34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-d-data-de-identified-no-radio-button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-d-data-de-identified-no-radio-button&quot;]</value>
      <webElementGuid>558c3af3-6fdb-48ed-bbf5-999623a3b40f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
