<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ExpctdPubliDate-Clndr</name>
   <tag></tag>
   <elementGuidId>f179027c-ed7e-4d79-ae31-cb88ac29cc11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-d-expected-publication-date&quot;]//following::button[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;section-d-expected-publication-date&quot;]//following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-d-expected-publication-date&quot;]//following::button[1]</value>
      <webElementGuid>1c98cd7d-67e4-4278-a736-9ffed94f8846</webElementGuid>
   </webElementProperties>
</WebElementEntity>
