<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TragetSubmDelivryDate-Clnder</name>
   <tag></tag>
   <elementGuidId>c1323b07-56a7-4349-8167-56d05dac8e45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;section-d-targeted-data-submission-delivery-date&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;section-d-targeted-data-submission-delivery-date&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;section-d-targeted-data-submission-delivery-date&quot;]</value>
      <webElementGuid>82539f32-3c03-41f2-a2f6-0615e729e626</webElementGuid>
   </webElementProperties>
</WebElementEntity>
