<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BannerTitle</name>
   <tag></tag>
   <elementGuidId>6ca68db2-a745-4b20-8476-c813ef0f8e52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()='Purpose']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()='Purpose']</value>
      <webElementGuid>86bf5fc8-d99d-4348-8025-81358cb240a7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
