<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PurposeDescription1</name>
   <tag></tag>
   <elementGuidId>8b28adbb-4f06-461e-b798-1851dbeaca87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()='Purpose']/following::span/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()='Purpose']/following::span/div[1]</value>
      <webElementGuid>e31e6617-9f33-4efe-8b9a-bce77cc71624</webElementGuid>
   </webElementProperties>
</WebElementEntity>
