<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PurposeDescription2</name>
   <tag></tag>
   <elementGuidId>85ab7242-ea81-4e9a-9349-fef3f12ccc73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()='Purpose']/following::span/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()='Purpose']/following::span/div[2]</value>
      <webElementGuid>6ae312f0-2fd0-431f-b51a-5c386710951b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
