<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Diagnosis-Facet</name>
   <tag></tag>
   <elementGuidId>a84a38ea-23a0-42fb-bbe8-2b1cafbfd92d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[text()=&quot;Diagnosis&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[text()=&quot;Diagnosis&quot;])[1]</value>
      <webElementGuid>e828181a-8e97-443b-9d2b-a9b440f968f7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
