<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Study_Facet</name>
   <tag></tag>
   <elementGuidId>503c6957-631b-4d17-88d4-148313620d92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[text()=&quot;Study&quot;])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[text()=&quot;Study&quot;])</value>
      <webElementGuid>cdcb5ff8-e99a-413f-a9b4-a59aef6ab20f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
