<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Study_Facet</name>
   <tag></tag>
   <elementGuidId>503c6957-631b-4d17-88d4-148313620d92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[text()=&quot;Study&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[text()=&quot;Study&quot;])[1]</value>
      <webElementGuid>035c992f-3d5f-4d06-9dce-e7c9595c852b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
