<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Asian_Chkbx</name>
   <tag></tag>
   <elementGuidId>5314e21d-7f32-48e8-b851-9b1d1ed1cd03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='checkbox_Race_Asian']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='checkbox_Race_Asian']</value>
      <webElementGuid>e067fabd-0348-4a6b-819d-921d6bedeaca</webElementGuid>
   </webElementProperties>
</WebElementEntity>
