<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>White_Chkbx</name>
   <tag></tag>
   <elementGuidId>fef13c2f-c1c9-4924-ab8f-580c25920acd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='checkbox_Race_White']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='checkbox_Race_White']</value>
      <webElementGuid>cd56a99e-793b-4fa9-97f2-7eec00e1e271</webElementGuid>
   </webElementProperties>
</WebElementEntity>
