<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Resources_HereLink</name>
   <tag></tag>
   <elementGuidId>be9d499e-f770-4817-b7e8-05e244ce5c42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@title='here']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@title='here']</value>
      <webElementGuid>1cd080a1-1b9b-446c-95f9-0e5ac54ab2ab</webElementGuid>
   </webElementProperties>
</WebElementEntity>
