<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Trials_WarningContinue_Btn</name>
   <tag></tag>
   <elementGuidId>83da68d8-1c3d-447f-a0b4-a0f8ab215928</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[.='Continue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[.='Continue']</value>
      <webElementGuid>8b472961-71d2-4eb8-b38a-10534684bf4a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
