<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Table-Headers</name>
   <tag></tag>
   <elementGuidId>19b9f197-acdc-420e-b6d1-068522a4bb6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//thead/tr/th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//thead/tr/th</value>
      <webElementGuid>2bb23e5a-ebde-423a-bbb1-3ecedca18739</webElementGuid>
   </webElementProperties>
</WebElementEntity>
