<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Canine_myFiles_TblHdr</name>
   <tag></tag>
   <elementGuidId>5a7f1b1c-adc1-4cb0-9d83-d3180418566a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table/thead</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table/thead</value>
      <webElementGuid>cacbcbb0-7fc5-4c0e-b6e5-a73704da7564</webElementGuid>
   </webElementProperties>
</WebElementEntity>
