<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GraphQLLink</name>
   <tag></tag>
   <elementGuidId>91db4407-25e4-467a-b18b-c4b00de5f477</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@href,'graphql')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@href,'graphql')]</value>
      <webElementGuid>bf83f723-f782-411b-9870-4823d24c99d8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
