<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BannerTitle</name>
   <tag></tag>
   <elementGuidId>24a7d371-2a88-4647-b193-c1363e5dbbb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()='GraphQL']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()='GraphQL']</value>
      <webElementGuid>c8603e0d-07b8-4cdd-ac5d-d1013261fa9f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
