<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TARGET_NBL-Chkbx</name>
   <tag></tag>
   <elementGuidId>e97fd0fd-103b-4dcb-8569-e954ec944d3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Acronym_TARGET_NBL&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Acronym_TARGET_NBL&quot;]</value>
      <webElementGuid>4aefd930-0ff5-4bb5-ba0d-59c624c4ad81</webElementGuid>
   </webElementProperties>
</WebElementEntity>
