<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Diagnosis-Facet</name>
   <tag></tag>
   <elementGuidId>bd6ff103-77ba-439d-bcb9-efd8d4a5c566</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()=&quot;Diagnosis&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()=&quot;Diagnosis&quot;]</value>
      <webElementGuid>1c9e1ab7-ec84-44b9-82ba-d05c5d8ce84c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
