<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CardTitle2</name>
   <tag></tag>
   <elementGuidId>a69e5998-006b-44ba-9d95-2635d4b830b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//h3)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//h3)[2]</value>
      <webElementGuid>00088213-935a-46c0-afd4-fd2e52ca85ed</webElementGuid>
   </webElementProperties>
</WebElementEntity>
