<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CardTitle1</name>
   <tag></tag>
   <elementGuidId>c4551f86-d05d-49f4-ba2b-464d194b1b2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//h3)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//h3)[1]</value>
      <webElementGuid>e2b5c318-2bc9-4156-956d-04b03c391ac8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
