<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CardTitle3</name>
   <tag></tag>
   <elementGuidId>647ef812-7b88-4f58-9217-255003abec81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//h3)[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//h3)[3]</value>
      <webElementGuid>55fc62e1-b5f3-483e-9980-cab2b8eb84bc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
