<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CardTitle4</name>
   <tag></tag>
   <elementGuidId>c4af0f0f-9755-472d-8fc2-efae2a3d99b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//h3)[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//h3)[4]</value>
      <webElementGuid>25bd91cc-908e-47af-ad63-b96d62363701</webElementGuid>
   </webElementProperties>
</WebElementEntity>
