<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SupportDescription</name>
   <tag></tag>
   <elementGuidId>4f030b9a-edd7-4752-81fd-67a496ab6f69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()='Support']/following::span/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()='Support']/following::span/div[1]</value>
      <webElementGuid>ebfcaf06-04a4-42db-93bc-89a4be28ae51</webElementGuid>
   </webElementProperties>
</WebElementEntity>
