<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Participants_ResultsTab</name>
   <tag></tag>
   <elementGuidId>ff0bfc90-39ac-42bf-8101-9c6019535ca6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div[2]/div[2]/div/div[2]/div/div[5]/div/div/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div[2]/div[2]/div/div[2]/div/div[5]/div/div/button[1]</value>
      <webElementGuid>391887ae-397a-44e1-b7ce-cfc82b61a4e9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
