<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sex_Drdn</name>
   <tag></tag>
   <elementGuidId>ea971a09-3935-45f2-9db5-b6dff4b7848d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;Sex&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;Sex&quot;]</value>
      <webElementGuid>8ff96d82-d4ba-40f9-b0aa-67bf7e412322</webElementGuid>
   </webElementProperties>
</WebElementEntity>
