<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>APP1059804</name>
   <tag></tag>
   <elementGuidId>db671c0c-5cef-44bf-9e2e-51d300452917</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;Study&quot;]/div[2]/div/div/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;Study&quot;]/div[2]/div/div/div/div[3]</value>
      <webElementGuid>137fd8ab-320a-4c8c-b7c5-e8edd5aa7b99</webElementGuid>
   </webElementProperties>
</WebElementEntity>
