<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DataElementsLink</name>
   <tag></tag>
   <elementGuidId>31dc6fef-0686-4dbc-b352-eb194c4a8f87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@title='here']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@title='here']</value>
      <webElementGuid>c11d8ba9-75f4-4266-874d-903f76cd4b8b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
