<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CCDIEmailLink</name>
   <tag></tag>
   <elementGuidId>3affade1-7796-4dab-81e6-7aa35397c1ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[contains(@href,'initiative@mail.nih.gov')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[contains(@href,'initiative@mail.nih.gov')])[1]</value>
      <webElementGuid>619580a7-16fe-4ac7-955e-8b3f2acb387a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
