<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DataAccessLink</name>
   <tag></tag>
   <elementGuidId>a8683a42-901a-4873-b35f-bc0fe574991a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@href,'Data_Access')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@href,'Data_Access')]</value>
      <webElementGuid>c44b21d1-b3b9-48d6-b15d-c4009d22f66f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
