<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubmissionsDGABLink</name>
   <tag></tag>
   <elementGuidId>59b16e77-cbd4-48ac-a97d-8c400f9835fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@title='(DGAB)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@title='(DGAB)']</value>
      <webElementGuid>3572b4cb-47ec-41bf-8d83-eeec8522165c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
