<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IndicationForStudy_Chkbx</name>
   <tag></tag>
   <elementGuidId>fdd34628-5841-49f2-b147-dabd1c71eec9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Race_Asian&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Race_Asian&quot;]</value>
      <webElementGuid>82531906-af5d-4d80-a9f5-535b015720c9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
