<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ReadAndAcceptPopUp-Btn</name>
   <tag></tag>
   <elementGuidId>b3d2fb98-13b7-4922-98bd-2dedc64dffc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;error-dialog-delete-button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;error-dialog-delete-button&quot;]</value>
      <webElementGuid>a972c63e-69b6-4aaa-b2fe-62766f2e038a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
