<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BannerTitle</name>
   <tag></tag>
   <elementGuidId>bfa0017f-693a-4b93-87cc-16d08f4ce645</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>67ed2905-4eea-43a0-b6c9-e86cfaaec14d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
