<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SpotlightDescription2</name>
   <tag></tag>
   <elementGuidId>34a759ea-88fa-465b-ba95-dbe38d18a1a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//h2)[2]/following-sibling::p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//h2)[2]/following-sibling::p</value>
      <webElementGuid>0eb1cbe2-ac68-4ba5-974f-c6e5c073ceeb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
