<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SpotlightTitle2</name>
   <tag></tag>
   <elementGuidId>83d8c805-65da-404c-878e-a1cee5b5b8a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//h2)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//h2)[2]</value>
      <webElementGuid>0dbcce3a-cb62-4f63-92e6-e84e1f85982e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
