<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PbacOptions-Chkbx</name>
   <tag></tag>
   <elementGuidId>4a339fae-6e6c-476c-9904-6a804cc3cfca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>4ca9b8b4-7ff2-4bce-b098-dfc6f1d064be</webElementGuid>
   </webElementProperties>
</WebElementEntity>
