<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BioinformaticsLink</name>
   <tag></tag>
   <elementGuidId>5cac97fa-4d3f-4683-8a96-987ba2634f79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@title='icdc-bioinformatics']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@title='icdc-bioinformatics']</value>
      <webElementGuid>2d022cd4-b6cf-4089-9398-58c0474625c5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
