<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GithubTitle</name>
   <tag></tag>
   <elementGuidId>363c2549-6f49-4cc7-9ceb-23cda436a92e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[text()='GitHub']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[text()='GitHub']</value>
      <webElementGuid>6b1f8808-acbd-488f-a8fe-5b4b331863e6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
