<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GraphqlLink</name>
   <tag></tag>
   <elementGuidId>30a261a9-0a50-463b-9550-1e2d6d0f06ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@title,'graphql')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@title,'graphql')]</value>
      <webElementGuid>5615b2b4-f6e5-4e1c-a01f-844f727b3b10</webElementGuid>
   </webElementProperties>
</WebElementEntity>
