<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cancel-Btn</name>
   <tag></tag>
   <elementGuidId>075bb0ff-079d-49ef-a69d-6f0637f2fa61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[.='Cancel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[.='Cancel']</value>
      <webElementGuid>5ec2c457-ec47-4a7d-bfbf-7de693c76857</webElementGuid>
   </webElementProperties>
</WebElementEntity>
