<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Release-Btn</name>
   <tag></tag>
   <elementGuidId>2630d547-fb83-46af-9398-6a2f36b63e14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[.='Release']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[.='Release']</value>
      <webElementGuid>3a12069b-1033-4fab-980a-f5abc49dc684</webElementGuid>
   </webElementProperties>
</WebElementEntity>
