<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubmitYes-Btn</name>
   <tag></tag>
   <elementGuidId>17fa9f32-83d2-455e-8e69-73e054ceca45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[.='Yes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[.='Yes']</value>
      <webElementGuid>2c84dfae-dc96-49a0-9fc9-a924724674e5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
