<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Treatment-Facet</name>
   <tag></tag>
   <elementGuidId>e0137f42-915c-4330-b00f-3b8cd4a7e25c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()=&quot;Treatment&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()=&quot;Treatment&quot;]</value>
      <webElementGuid>daac698f-7ca5-4a00-bf37-5ad7aaa4d24e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
