<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ResourceName</name>
   <tag></tag>
   <elementGuidId>5d38e737-73a1-4ddc-bc54-3a32afd90565</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class='prDetailHeaderLabel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='prDetailHeaderLabel']</value>
      <webElementGuid>66d6fbb2-0b56-4fea-ab7d-a94c8e3d7685</webElementGuid>
   </webElementProperties>
</WebElementEntity>
