<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ContactDescription</name>
   <tag></tag>
   <elementGuidId>cccde3c9-3490-42ff-a214-e6010bfe0704</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()='Support']/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()='Support']/following::div[1]</value>
      <webElementGuid>8a0e41a1-17d0-45e0-b8f5-c499bcef1b92</webElementGuid>
   </webElementProperties>
</WebElementEntity>
