<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubmissionLink</name>
   <tag></tag>
   <elementGuidId>3e19fadc-052a-48b6-95d0-c46912020327</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@href,'ICDC_DGAB')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@href,'ICDC_DGAB')]</value>
      <webElementGuid>003a3a1b-074f-4b39-babf-b409f25491e1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
