<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ResourcesParagraph4</name>
   <tag></tag>
   <elementGuidId>683505f7-32ab-40f0-a808-135d1a3c6bb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='CCDI']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='CCDI']</value>
      <webElementGuid>88a097d3-03e3-4547-b024-0816ebf73aa5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
