<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ResourcesTitle</name>
   <tag></tag>
   <elementGuidId>58cfc45f-1286-4333-8055-224c4651824a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='introTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='introTitle']</value>
      <webElementGuid>1b55afd0-8492-4134-b159-d0df25d23d7b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
