<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Trials_FilesTable_Hdr</name>
   <tag></tag>
   <elementGuidId>4a5ee770-d825-415e-a2d7-f9fce8c3282c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='table_case_detail']//parent::div//parent::span//parent::th//parent::tr//parent::thead</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='table_case_detail']//parent::div//parent::span//parent::th//parent::tr//parent::thead</value>
      <webElementGuid>12cc5837-70d3-49ac-8375-75515151d8a9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
