<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CancerMoonshotLink</name>
   <tag></tag>
   <elementGuidId>861bbdfe-1c46-4664-9731-d85cb66a0ed2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href='https://www.cancer.gov/research/key-initiatives/moonshot-cancer-initiative']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@href='https://www.cancer.gov/research/key-initiatives/moonshot-cancer-initiative']</value>
      <webElementGuid>fc21d061-2b72-4b5c-a72f-55c5841a1aeb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
