<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ContactSection</name>
   <tag></tag>
   <elementGuidId>a299e399-17ee-484e-a299-5946f50c7b13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class='aboutPageSectionContent'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class='aboutPageSectionContent'])[2]</value>
      <webElementGuid>d12673b9-b2f9-43b2-811e-161fb9b0b833</webElementGuid>
   </webElementProperties>
</WebElementEntity>
