<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DataSharingLink</name>
   <tag></tag>
   <elementGuidId>7d35793b-938a-4c80-88a5-a50412fae325</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href='https://datascience.cancer.gov/about/organization#ods']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@href='https://datascience.cancer.gov/about/organization#ods']</value>
      <webElementGuid>7b7dab5c-23c8-4c4c-8e25-b0c51a8af66a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
