<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FeedbackEmailLink</name>
   <tag></tag>
   <elementGuidId>ca656b74-a2df-4dc2-8baa-ab65d6a16ca3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h2[@class='disclaimerHeader']/following-sibling::p/a[@href='mailto:nciofficeofdatasharing@mail.nih.gov?Subject=Index%20of%20NCI%20Studies%20feedback']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h2[@class='disclaimerHeader']/following-sibling::p/a[@href='mailto:nciofficeofdatasharing@mail.nih.gov?Subject=Index%20of%20NCI%20Studies%20feedback']</value>
      <webElementGuid>4f991a53-d3f2-4180-9380-4c1bf45dc98a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
