<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FunctionalitySection</name>
   <tag></tag>
   <elementGuidId>0b93e8bd-e2d2-4ac6-8347-560d4759a95b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class='aboutPageSectionContent'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class='aboutPageSectionContent'])[1]</value>
      <webElementGuid>eb4b639d-7d93-4291-871d-c6a8bb263a1d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
