<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Grants_ReporterLink</name>
   <tag></tag>
   <elementGuidId>20128d93-d3e9-4d06-b41f-ee09904c7bcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[@href='https://reporter.nih.gov/'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[@href='https://reporter.nih.gov/'])[1]</value>
      <webElementGuid>f7d368e1-fce6-491f-842e-558723bf8f94</webElementGuid>
   </webElementProperties>
</WebElementEntity>
