<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ObjectivesParagraph3</name>
   <tag></tag>
   <elementGuidId>450453db-f3ba-4cfa-a8f6-82597fcfdd5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@class='aboutPageDisclaimerItems']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@class='aboutPageDisclaimerItems']</value>
      <webElementGuid>17289595-a4fe-4b8f-bb8c-b668160b5229</webElementGuid>
   </webElementProperties>
</WebElementEntity>
