<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ObjectivesParagraph2</name>
   <tag></tag>
   <elementGuidId>4b563d32-cadc-4b50-81b8-826c17fb9649</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h2[@class='disclaimerHeader']/following-sibling::p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h2[@class='disclaimerHeader']/following-sibling::p[2]</value>
      <webElementGuid>efa3c59f-cfe6-4235-8339-0aac86a10cef</webElementGuid>
   </webElementProperties>
</WebElementEntity>
