<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ObjectivesParagraph1</name>
   <tag></tag>
   <elementGuidId>d585f1fe-12ef-416a-968a-7cb36b326be6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h2[@class='disclaimerHeader']/following-sibling::p[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h2[@class='disclaimerHeader']/following-sibling::p[1]</value>
      <webElementGuid>61ca6901-2f29-495a-8db1-e6f37fef7431</webElementGuid>
   </webElementProperties>
</WebElementEntity>
