<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ObjectivesTitle</name>
   <tag></tag>
   <elementGuidId>1812f56b-a16a-4a3b-895f-eae6c614da5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h2[@class='disclaimerHeader']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h2[@class='disclaimerHeader']</value>
      <webElementGuid>1164ca78-9f5a-4637-88c9-64aff393edce</webElementGuid>
   </webElementProperties>
</WebElementEntity>
