<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Publications_PubmedLink2</name>
   <tag></tag>
   <elementGuidId>c9323719-a3f4-4e18-8851-abf9fa08f7e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[@href='https://pubmed.ncbi.nlm.nih.gov/'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[@href='https://pubmed.ncbi.nlm.nih.gov/'])[2]</value>
      <webElementGuid>055c508e-875b-4d1f-a97f-2cdc7350aac0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
