<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Publications_PubmedLink</name>
   <tag></tag>
   <elementGuidId>cffc62c1-4708-4d0f-8e3b-4d4988d01532</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[@href='https://pubmed.ncbi.nlm.nih.gov/'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[@href='https://pubmed.ncbi.nlm.nih.gov/'])[1]</value>
      <webElementGuid>522f29ff-e06b-41cc-9585-4ee8a7ada4e8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
