<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Publications_ReporterLink</name>
   <tag></tag>
   <elementGuidId>d88ef0b3-4fb9-4a47-b1e7-ef33f09dbb18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[@href='https://reporter.nih.gov/'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[@href='https://reporter.nih.gov/'])[2]</value>
      <webElementGuid>cff40b99-ff37-4451-b376-81ffebf81de1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
