<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ReporterFaqLink</name>
   <tag></tag>
   <elementGuidId>52d6283a-9bbe-40a9-8e7a-245214f4de68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href='https://report.nih.gov/faqs#:~:text=How%20are%20projects%20linked%20to%20Publications%3F']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@href='https://report.nih.gov/faqs#:~:text=How%20are%20projects%20linked%20to%20Publications%3F']</value>
      <webElementGuid>ab6b46f7-be2a-4978-bbe6-bcf16da95d90</webElementGuid>
   </webElementProperties>
</WebElementEntity>
