<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Takeaways_IciteLink</name>
   <tag></tag>
   <elementGuidId>a7930e0d-f90c-4e8a-808e-6327cb1ae72d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href='https://icite.od.nih.gov']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@href='https://icite.od.nih.gov']</value>
      <webElementGuid>bbfef61a-e467-4f30-b4de-15e98e935d10</webElementGuid>
   </webElementProperties>
</WebElementEntity>
