<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TakeawaysSection</name>
   <tag></tag>
   <elementGuidId>e6bac513-c7cd-49e3-89d5-3009a3c2798d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='keyTakeawaysSection']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='keyTakeawaysSection']</value>
      <webElementGuid>098070ff-f804-443f-a993-a9a162d548a7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
