<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Takeaways_DbgapLink</name>
   <tag></tag>
   <elementGuidId>04d8f272-58a6-401a-b4e3-7001aaa39268</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[@href='https://www.ncbi.nlm.nih.gov/gap/'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[@href='https://www.ncbi.nlm.nih.gov/gap/'])[1]</value>
      <webElementGuid>fde6dce4-385f-4f7d-bd53-65e0e4ec4a9d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
