<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SpotlightPanelLink3</name>
   <tag></tag>
   <elementGuidId>24238d06-d9b2-47cc-91c6-7ec9f88376ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,'MuiPaper-elevation')])[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,'MuiPaper-elevation')])[3]/a</value>
      <webElementGuid>8e6db409-3a68-4ed3-a65a-61434a2b330d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
