<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Study_Facet</name>
   <tag></tag>
   <elementGuidId>cd792c15-7804-43ca-9424-f0c18c252457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()=&quot;Study&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()=&quot;Study&quot;]</value>
      <webElementGuid>d5746e49-515b-490f-88b0-a504e0dd236d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
