<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CGCLink</name>
   <tag></tag>
   <elementGuidId>eddd3439-5649-402e-8370-2edab217c26c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@href,'seven-bridges')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@href,'seven-bridges')]</value>
      <webElementGuid>dd511e03-ecac-40d4-84dc-f52dc7b5c584</webElementGuid>
   </webElementProperties>
</WebElementEntity>
