<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FAIRLink</name>
   <tag></tag>
   <elementGuidId>a07b850c-2948-4334-a989-fd71c636a4b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@href,'fair')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@href,'fair')]</value>
      <webElementGuid>04143d68-7183-4cdd-bfd6-97f1621910a1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
