<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Files-Tbl</name>
   <tag></tag>
   <elementGuidId>b46d2d55-fb26-4feb-9b8b-615ee3b66039</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;file_tab_table&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;file_tab_table&quot;]</value>
      <webElementGuid>91c66cdf-54c6-4632-9a3e-a9d492098411</webElementGuid>
   </webElementProperties>
</WebElementEntity>
