<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Participants-Tbl</name>
   <tag></tag>
   <elementGuidId>64983bf5-fa32-4359-9115-2659c6326f54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;participants_tab_table&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;participants_tab_table&quot;]</value>
      <webElementGuid>aa01b918-d9b8-4bc7-8c0c-26184b804825</webElementGuid>
   </webElementProperties>
</WebElementEntity>
