<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Participants-TblHdr</name>
   <tag></tag>
   <elementGuidId>a9ef8fd0-7e15-4db7-8cea-7934a496b907</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;participants_tab_table&quot;]//thead</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;participants_tab_table&quot;]//thead</value>
      <webElementGuid>df8fc931-26b1-42a9-b31a-2801afa6f3b3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
