<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ManageStudies-Btn</name>
   <tag></tag>
   <elementGuidId>e04e5f0d-83c2-46ca-8d35-5871afce4c46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;navbar-dropdown-item-studies-manage&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;navbar-dropdown-item-studies-manage&quot;]</value>
      <webElementGuid>3b0b4073-aceb-49c8-9be4-9e9085ae0aba</webElementGuid>
   </webElementProperties>
</WebElementEntity>
