<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ManagePrograms-Btn</name>
   <tag></tag>
   <elementGuidId>2a512f47-05ec-4603-9c7b-94ad1a4d69df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;navbar-dropdown-item-program-manage&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;navbar-dropdown-item-program-manage&quot;]</value>
      <webElementGuid>537ff61f-1aa3-4c93-a9a1-b9e585548918</webElementGuid>
   </webElementProperties>
</WebElementEntity>
