<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ManageUsers-Btn</name>
   <tag></tag>
   <elementGuidId>a68fe818-3de7-4068-a476-15d6e601af36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;navbar-dropdown-item-user-manage&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;navbar-dropdown-item-user-manage&quot;]</value>
      <webElementGuid>484ffe66-1195-4be5-aa10-4e484a179980</webElementGuid>
   </webElementProperties>
</WebElementEntity>
