<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bento_About-Btn</name>
   <tag></tag>
   <elementGuidId>680704fa-9116-4fc6-96b9-58f85b59e3cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'navbar_dropdown_about']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@href,'cases')]</value>
      <webElementGuid>31490e25-cbdc-4fdc-bee6-03aa7cbe0e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navbar_dropdown_about</value>
      <webElementGuid>7f14764b-9903-448a-9b37-5044aa121b7d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
