<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Survival-Facet</name>
   <tag></tag>
   <elementGuidId>e50456ec-8b82-42e5-843f-df065ee55eaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[text()=&quot;Survival&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[text()=&quot;Survival&quot;])[1]</value>
      <webElementGuid>c47356db-3a23-4448-a018-003949c19c5a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
