<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>APP1059804</name>
   <tag></tag>
   <elementGuidId>56936c15-354e-42b3-a5f4-6706e5c4e540</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;Study&quot;]/div[2]/div/div/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;Study&quot;]/div[2]/div/div/div/div[3]</value>
      <webElementGuid>1ecc1f09-e8bc-4ceb-ba6d-c63b8177fb72</webElementGuid>
   </webElementProperties>
</WebElementEntity>
