<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Stanford-Chkbx</name>
   <tag></tag>
   <elementGuidId>d9428357-aa7a-4578-b663-27ae00a765db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Institution_Stanford&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;checkbox_Institution_Stanford&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Institution_Stanford&quot;]</value>
      <webElementGuid>afff34ef-9178-43ed-ae58-a56cddf69b25</webElementGuid>
   </webElementProperties>
</WebElementEntity>
