<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Studies_Cnt</name>
   <tag></tag>
   <elementGuidId>1f34059d-1625-4121-8869-28fee39bd623</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='statsbar_count_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='statsbar_count_1']</value>
      <webElementGuid>c0c929cf-83e4-44db-b2e5-18d06fc23850</webElementGuid>
   </webElementProperties>
</WebElementEntity>
