<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DBGAPLink</name>
   <tag></tag>
   <elementGuidId>b176e4cf-54bf-4cd6-81f0-85a68835ad7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@title='dbGaP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@title='dbGaP']</value>
      <webElementGuid>fe4c3164-a7f8-4c14-9e56-330f058b2f62</webElementGuid>
   </webElementProperties>
</WebElementEntity>
