<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Ethnicity-Ddn</name>
   <tag></tag>
   <elementGuidId>c3b9fa76-9114-4d99-8b2d-e1eabcac6976</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@id=&quot;Ethnicity&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@id=&quot;Ethnicity&quot;])[1]</value>
      <webElementGuid>9633ceb0-7e38-49f5-adc7-39fa26713497</webElementGuid>
   </webElementProperties>
</WebElementEntity>
