<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Unknown-Chkbx</name>
   <tag></tag>
   <elementGuidId>bd38e255-c1d8-45f3-a162-72a5cf11af25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkbox_Ethnicity_Unknown&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkbox_Ethnicity_Unknown&quot;]</value>
      <webElementGuid>6dc6fc4f-3902-4884-b58c-5063f03956ae</webElementGuid>
   </webElementProperties>
</WebElementEntity>
