<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CCDI_Diagnosis_TblHdr</name>
   <tag></tag>
   <elementGuidId>3033e4ac-5aff-48d5-83bc-da44a26b267c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;diagnosis_tab_table&quot;]//thead</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;diagnosis_tab_table&quot;]//thead</value>
      <webElementGuid>6acaa16b-a9ce-43f4-b1ed-3ec345c52d22</webElementGuid>
   </webElementProperties>
</WebElementEntity>
