<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Participants_ResultsTab</name>
   <tag></tag>
   <elementGuidId>1467d433-2858-4da1-974d-6064b3ce9057</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div[2]/div[2]/div/div[2]/div/div[5]/div/div/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div[2]/div[2]/div/div[2]/div/div[5]/div/div/button[1]</value>
      <webElementGuid>6d16a78a-1805-4199-a365-d0f5bce66a51</webElementGuid>
   </webElementProperties>
</WebElementEntity>
