<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Studies_ResultsTab</name>
   <tag></tag>
   <elementGuidId>c3e0d02f-c0b9-4cb5-b1d4-11da038880f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div[2]/div[2]/div/div[2]/div/div[6]/div/div/button[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div[2]/div[2]/div/div[2]/div/div[6]/div/div/button[3]</value>
      <webElementGuid>1a0cc9aa-3aba-44d1-b845-3cda4f5045b8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
